### ISSUE TITLE
Customizable "next" key as a command line parameter

### ISSUE THREAD

**Issue by staaas** [inglesp/prescons#8]
It makes sense to add a command line parameter for "next" key customization. Current value is `space` key.

It makes sense for wireless presenters as they are usually work as an external keyboard with a limited amount of keys.

I suggest we can use [docopt](https://github.com/docopt/docopt) for parsing command line arguments.

**Comment by inglesp** [comment]
Are there any keyboards without a spacebar?  I can see that it'd be useful to be able to integrate with a clicky thing though, but I think that'd be more work than just customising the "next" key.
